services:
  #数据库
  db:
    image: mysql:5.7
    container_name: bingjikeji-db
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=7405
      - MYSQL_DATABASE=bingjikeji
    restart: always
    ports:
      - 3307:3306
    # 初始命令
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    # 数据挂载
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - ./server/init:/docker-entrypoint-initdb.d/

  #后端服务
  server:
    container_name: bingjikeji-server
    environment:
      - TZ=Asia/Shanghai
    build:
      context: ./server
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: always

  #前端服务
  front:
    container_name: bingjikeji-front
    environment:
      - TZ=Asia/Shanghai
    build:
      context: .
    depends_on:
      - server
    ports:
      - 80:80
    restart: always
