version:  '3'
services:
  #数据库
  webdb:
    image: mysql:5.7
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=7405
      - MYSQL_DATABASE=bingjikeji
    restart: always
    ports:
      - 8891:3306
    # 初始命令
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    # 数据挂载
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - ./server/init:/docker-entrypoint-initdb.d/
    networks:
      - front-tier
      - back-tier

  #后端服务
  webserver:
    environment:
      - TZ=Asia/Shanghai
    build:
      context: ./server
    depends_on:
      - webdb
    ports:
      # https端口映射 8890
      - 8890:8890
      # http端口映射 8888
      - 8888:8888
    volumes:
      - /data/serve/upload:/app/static/upload
    networks:
      - front-tier
      - back-tier
    restart: always

  #前端服务
  webfront:
    environment:
      - TZ=Asia/Shanghai
    build:
      context: .
    depends_on:
      - webserver
    ports:
      - 8889:80
    networks:
      - front-tier
      - back-tier
    restart: always

networks:
    front-tier:
      driver: bridge
    back-tier:
      driver: bridge